### ISSUE TITLE
Please support shebang for scripting

### ISSUE THREAD

**Issue by kseistrup** [fubark/cyber#12]
`cyber` doesn't seem to support shebangs (`#!`):

I can run the `fibonacci.cy` script manually:

```sh
» cyber fibonacci.cy
832040
```

However, when I add `#!/usr/bin/env cyber` to the top of the script — in the hope that I can run it just like any other script — all I get is a segfault:

```sh
» ./fibonacci.cy
'./fibonacci.cy' terminated by signal SIGSEGV (Address boundary error)
```

And the same thing happens when I run the modified script manually:

```sh
» cyber fibonacci.cy
'cyber fibonacci.cy' terminated by signal SIGSEGV (Address boundary error)
» cyber version
Cyber 0.1 build-203-c483853
```

Edit: added cyber version

**Comment by fubark** [comment]
This should be fixed.

**Comment by kseistrup** [comment]
Whauw, that was fast — thanks a lot!
