### ISSUE TITLE
Issue with incrementing variable by 1

### ISSUE THREAD

**Issue by sts10** [fubark/cyber#14]
I might be missing something, but when I throw this in the playground
```
i = 0 
print i 
i = i + 1
print i
```
I get
```
0
2
```
I would expect
```
0
1
```

I got here after having some issues with a `for` loop at the end of [this little script](https://github.com/sts10/ticy-tacy-toe).

**Comment by sts10** [comment]
Ah, `i += 1` works as expected, it seems.

**Comment by fubark** [comment]
This should be fixed. It was working inside function blocks before, this fix is for the main block.
