### ISSUE TITLE
how to build it under Debian?

### ISSUE THREAD

**Issue by OrionRandD** [fubark/cyber#22]
How do I build/install it under Debian?
Thx

**Comment by fubark** [comment]
I'll be looking into writing an install script soon. For building: https://github.com/fubark/cyber/blob/master/docs/build.md

**Comment by OrionRandD** [comment]
> I'll be looking into writing an install script soon. For building: https://github.com/fubark/cyber/blob/master/docs/build.md

Waiting... Sigh...
Pehaps advertising in Debian offficial channels could prompt a dev to write a deb package. Just a suggestion...

**Comment by fubark** [comment]
You can use the install script: https://github.com/fubark/cyber#install
Or build from source here: https://github.com/fubark/cyber/blob/master/docs/build.md
