### ISSUE TITLE
Make PR to kostya/benchmarks repo

### ISSUE THREAD

**Issue by dumblob** [fubark/cyber#29]
The repo https://github.com/kostya/benchmarks is kind of a state-of-the-art of non-rigorous but "closer to real practice" benchmarking.

It would be great to see Cyber there :wink:.

**Comment by fubark** [comment]
I don't really see the point of comparing to mostly compiled languages. Cyber is fast as a VM interpreter.

**Comment by dumblob** [comment]
1. It is actually **not** mostly compiled languages - see Ruby, Java, Python, Lua, Racket, Kotlin, F#/.NET, Ocaml (both interpreted & compiled), Julia, Haskell, Node.js, Elixir, and I could go on (I did not count, but it feels that most are actually interpreted).
2. The benchmark is focused on real-world perception where - whatever your social bubble is - interpreted languages compete with compiled languages all the time.

Feel free to reopen this issue so that someone can pick it up if not you :wink:.
