### ISSUE TITLE
Cyber Core dumped when running the loop example from the docs 

### ISSUE THREAD

**Issue by dhensen** [fubark/cyber#39]
![image](https://user-images.githubusercontent.com/2786295/215791437-9c197b92-44c7-4eb0-a5d0-9abd28b422e7.png)

**Comment by fubark** [comment]
This is fixed in bcc6bb81a8fc517a13d6b3a69432238c801fad95.
It should now panic like this:
```text
panic: Missing method symbol `iterator` from receiver of type `none`.

foo.cy:1:5 main:
for items each it:
    ^
```
