### ISSUE TITLE
Unexpected List Behavior 

### ISSUE THREAD

**Issue by zachcp** [fubark/cyber#4]
Seems like the remove operator has an issue....

```
all_data = [1,2,3,4]

print all_data

for all_data as d:
    print d

print("Remove an item ... ")

all_data.remove(1)

for all_data as d:
    print d


```

```sh
List (4)
1
2
3
4
Remove an item ... 
1
2
2
```

**Comment by fubark** [comment]
This is fixed. It also does an index check and returns error(#OutOfBounds), but this might change in the future since it's inconsistent with index access out of bounds which is a panic.
