### ISSUE TITLE
Some more if/else weirdness

### ISSUE THREAD

**Issue by sts10** [fubark/cyber#41]
I was refactoring [a function](https://github.com/sts10/cyber-tack/blob/main/run.cy#L68-L72) and found some weirdness with `if`/else` branches in a `for` loop.

In the playground, this outputs nothing.
```text
my_arr = [4,5,6,7,8]
what_i_found = find_6_or_7(my_arr)
print 'Found: {what_i_found}' 

func find_6_or_7(an_arr):
    for an_arr each item:
        if item == 6:
            return 6
        else item == 7:
            return 7
```

But if I change the `else` to a second `if`, it runs as expected:
```text
my_arr = [4,5,6,7,8]
what_i_found = find_6_or_7(my_arr)
print 'Found: {what_i_found}' 

func find_6_or_7(an_arr):
    for an_arr each item:
        if item == 6:
            return 6
        if item == 7:
            return 7
```

Using 2 `if`s in this particular example isn't any less efficient than a `if` and `else`, but I think there are cases where it would be.

This time, I checked: I use all spaces for indents here.

**Comment by fubark** [comment]
This should be fixed in 3343587e2ae6a0e9fdfa7e46d3f620222288f7cb.
