### ISSUE TITLE
Print without inserting a newline at the end?

### ISSUE THREAD

**Issue by sts10** [fubark/cyber#42]
It might be nice to have the option for `print` _not_ to insert a newline at the end. 

For example, in Python, `print` takes an optional end-character, allowing user to overwrite the default newline:
```python
print("hello, ", end='')
print("world")
```

In Go, we get a slightly different method:
```go
fmt.Printf("hello, ")
fmt.Printf("world")
```
And similarly in Rust, a slightly different macro: `print!("hello, ")`

Maybe a bit niche for so young a language, but it can be handy when using loops.

**Comment by fubark** [comment]
You can achieve this with `prints`. It's not currently emulated in the playground though, I should take a look at that...

**Comment by fubark** [comment]
This should be working now in the playground.
