### ISSUE TITLE
issues with sleep function

### ISSUE THREAD

**Issue by GabCores** [fubark/cyber#47]
hi , testing sleep function 

import os 'os'
sleeptime = 4000
while true:
  os.sleep(sleeptime)
  resp =  fetchUrl( url ) 
  print resp

delay is not working , no matter of sleeptime value 
May doing something wrong ?
thanks !

**Comment by fubark** [comment]
Are you on windows by chance, it's currently a no-op on Windows. I'll add that soon.

**Comment by GabCores** [comment]
yes it was on Windows . 
Testing and working on Linux , I'll continue on this OS .
thanks !

**Comment by fubark** [comment]
This was just added for Windows. Feel free to report any issues in a net ticket.
