### ISSUE TITLE
Question about fetchUrl

### ISSUE THREAD

**Issue by GabCores** [fubark/cyber#49]
hi there !, In Linux and Windows fetchUrl works as an asynchronous function 
Is this the expected outcome?
if so , all cyberscript functions are asynchronous ?
I know you mention that asynchronous management is on the road , but what is the native nature of the language ?
thanks!

**Comment by fubark** [comment]
fetchUrl is currently synchronous. If you're getting no response, then it's probably a bug with the builtin http client; you should post what url you're using if that's the case. You can also use os.execCmd if you have an installed http client like curl.

There will be an equivalent of await in the language, although the design hasn't been finalized. I don't think there would be a builtin async io library though. Instead, Cyber would provide the ability to create one by exposing an api for Promises.

**Comment by GabCores** [comment]
pls , try this sample 

while true:
  resp = fetchUrl('http://httpstat.us/200?sleep=10000')
  print resp 

no delay of 10s between calls 
what is wrong with this expectations ?

by the way , thanks for fixing sleep on Windows!

**Comment by fubark** [comment]
No problem!

This looks like the query parameter isn't sent. So it's actually doing this: `GET /200 HTTP/1.1` instead of this `GET /200?sleep=10000 HTTP/1.1` That's why you're getting a response so quickly. I'll make the fix now, one moment...

**Comment by GabCores** [comment]
now working fine!
