### ISSUE TITLE
Can't run on emscripten environment.

### ISSUE THREAD

**Issue by Andre-LA** [fubark/cyber#56]
Hello, I'm trying to run Cyber on the web using emscripten (because of the SDL2 port), however, I getting an runtime error on the process.

# Environment
- Tested on Fedora Linux 37.
- Zig version: 0.11.0-dev.1797+d3c9bfada (as described on build documentation).
- Cyber version: 9930caa
- Emscripten version: [at commit a2ccccba58918706f815d806460d09310fe236d9](https://github.com/emscripten-core/emsdk/commit/a2ccccba58918706f815d806460d09310fe236d9).

# Steps to reproduce
- Download the zig 0.11-dev compiler and clone cyber repository as described on [build documentation](https://github.com/fubark/cyber/blob/master/docs/build.md#dependencies).
- Build the wasm library [as described](https://github.com/fubark/cyber/blob/master/docs/build.md#build-as-a-library) on building documentation.
- Download and setup emscripten as described on [emscripten documentation](https://emscripten.org/docs/getting_started/downloads.html#download-and-install).
- Archive the `cyber.wasm.o` file using the command `emar -rcs libcyber.a zig-out/lib/cyber.wasm.o`.
- Create the C file with the code below, it's adapted from `examples/c-embedded/main.c`.
- Create the build directory, just for organization.
- Compile `main.c` with `emcc` with the command `emcc main.c ./libcyber.a -I./src/ -L. -o build/main.html`
- Run it with `cd build/ && emrun main.html`.

# Expected behaviour
The expected behaviour would be seeing this message on the page's console:
```
creating Cyber VM
Cyber VM created
2
Success!
```

# Observed behaviour
An exception it's thrown, with a stack trace available on the browser's console, on the page's console only `creating Cyber VM` it's shown, which means that the problem happens on `cyVmCreate` function call.

# Testing code
main.c:
```c
#include <stdio.h>
#include "cyber.h"

// host functions
void hostFetchUrl(const char *url, size_t urlLen) {}
void hostEvalJS(const char *ptr, size_t len) {}
void hostSleep(uint64_t secs, uint64_t nsecs) {}
void hostLogDebug(const char *ptr, size_t len) {}
void hostLogInfo(const char *ptr, size_t len) {}
void hostLogWarn(const char *ptr, size_t len) {}
void hostLogError(const char *ptr, size_t len) {}
double hostMilliTimestamp() {
    return 0.016;
}
void hostFileWrite(uint32_t fid, const char* str, size_t strLen) {
    printf("%s", str);
}

int main(void) {
    printf("creating Cyber VM\n");
    CyVM* vm = cyVmCreate();
    printf("Cyber VM created\n");
    CStr src = cstr(
        "a = 2\n"
        "print a"
    );
    CyValue val;
    int res = cyVmEval(vm, src, &val);
    if (res == CY_Success) {
        printf("Success!\n");
        cyVmRelease(vm, val);
    } else {
        CStr err = cyVmGetLastErrorReport(vm);
        printf("%s\n", err.charz);
    }
    cyVmDestroy(vm);
    return 0;
}
```

# Extra note
The code above works with [wasmtime](https://wasmtime.dev/), when using the [wasi-sdk](https://github.com/WebAssembly/wasi-sdk) with the same cyber build, with (almost) same [building steps](https://codeberg.org/Andre-LA/random-gists/src/commit/e8099bb54b0ab2e332ed2eae2a4523fb88b677d1/cyber/cyber-embedded-test.c#L4-L17).

**Comment by fubark** [comment]
As discussed on Discord, the issue is that Emscripten manages it's own memory while the library is compiled with it's own allocator. If this https://github.com/fubark/cyber/blob/15df569aaeb54d33590854c56fa44826769191b3/src/lib.zig#L32 is changed to `alloc = std.heap.c_allocator;` it should work. I guess we can also add a build option for this too.

**Comment by Andre-LA** [comment]
As discussed on discord, with the latest changes, alongside with the change of `wasm_allocator` to `c_allocator` on the cited line, the runtime works on emscripten without any problems.
