### ISSUE TITLE
Web Interpreter Can't Use Int Type

### ISSUE THREAD

**Issue by Capital-EX** [fubark/cyber#65]
Playing around with the online interpreter, it seems like the web build doesn't have access to the float time. Additionally, there is no warning nor error about this. So, I was confused when this code:

```cyber
func foobar(x int):
    print("Got a int")

func foobar(x float):
    print("Got a... float?")

foobar(1)
```

Always took the float path.

**Comment by fubark** [comment]
You may want to clear the web cache as I just uploaded latest.

```
func foobar(x int):
    print("Got a int")

func foobar(x float):
    print("Got a... float?")

foobar(1)
foobar(1.0)
```
```
Got a int
Got a... float?
success: 2ms
```

**Comment by Capital-EX** [comment]
Oh, nice! It's all fixed up for me now.
