### ISSUE TITLE
Cyber crashes (method with self parameter inside object)

### ISSUE THREAD

**Issue by shimamura-sakura** [fubark/cyber#71]
Version: release 0.3

This segfaults:
```
type A object:
    func b(self):
        pass
```
Removing `self` makes it don't crash.

Also, this doesn't segfault:
```
type A object:
    var i int
    func b(self):
        pass
```

I guess one shouldn't declare methods with `self` inside an object?

**Comment by fubark** [comment]
That's correct, it used to require `self` as a param but now you just use `self` inside the body. The fact that it's segfaulting for that is a bug, it should be a compile error instead.
