### ISSUE TITLE
Jupyter Kernel

### ISSUE THREAD

**Issue by ccleavinger** [fubark/cyber#75]
Hi, I've been interested in Cyber for a while!

Like many people I'm frustrated with the current python/pythonic landscape of AI. I feel like the versatility, speed, ease of interop with C, and embeddability of Cyber provide the foundation for a strong language in AI/ML. If implementing a Jupyter Kernel with [xeus](https://github.com/jupyter-xeus/xeus-zmq) sounds interesting/promising for the future of cyber please follow up and let me know!

I'd be more than happy to try and build the kernel out, though keep in mind it will most likely remain a toy kernel.

**Comment by fubark** [comment]
It would be nice to have a Jupyter kernel readily available to experiment with! I don't think there is one yet, although @DaelonSuzuka has expressed interest on discord (just a screenshot so far though).

**Comment by DaelonSuzuka** [comment]
> just a screenshot so far though

No, I actually implemented a jupyter/IPython plugin to run cyber in cells. It's published as part of my [cyberlang](https://pypi.org/project/cyberlang/) python package.

https://github.com/DaelonSuzuka/cyber-python/blob/master/example_notebook.ipynb

**Comment by ccleavinger** [comment]
I wasn't aware of the IPython plugin, that's some amazing work!
That pretty much answered my question, if we really want to offer a strong/fast option in Jupyter notebooks then investing in a kernel is a good idea. Otherwise it's pretty much non-essential.
Thanks @DaelonSuzuka!
