### ISSUE TITLE
Error occurs when compiling the examples - undefined symbol: execBytecode.

### ISSUE THREAD

**Issue by jub0t** [fubark/cyber#83]
```sh
D:\Cyber\examples\c-embedded>zig c++ main.cpp -I ../../src/include ../../zig-out/lib/cyber.lib -o ./main.exe
```

**RESULTS:**
```sh
LLD Link... lld-link: error: undefined symbol: execBytecode
>>> referenced by cyber.lib(cyber.lib.obj):(vm.evalLoopGrowStack)
```

**Comment by fubark** [comment]
This broke when the VM was separated from the lib. I have the fix mixed in with my other WIP changes, but for now 6d85e885 works.

**Comment by jub0t** [comment]
Thanks a lot for pointing it out, I already started to suspect the current commit version for the broken feature. Any ETA on it being fixed?

**Comment by fubark** [comment]
This should be fixed. Please reopen if you encounter more issues.
