### ISSUE TITLE
CLI / wasm

### ISSUE THREAD

**Issue by mationai** [fubark/cyber#90]
How do I compile to wasm?  Does cyber CLI have menu? Tried `-h`, `--help`, didn't work. The CLI section in doc is very lacking.

thanks

**Comment by fubark** [comment]
It's `cyber help`, but I suppose `-h` and `--help` should be aliases too. I will also update the CLI docs.

For building wasm, see the `build.md`. That is for standalone wasm which won't have any interop with web. `zig build web-lib` will produce the wasm with interop like the playground. In the future it will contain JS promise to Cyber futures and maybe DOM access, so I'd check back in a week or so.

**Comment by fubark** [comment]
I have added CLI instructions to the docs. Closing, thanks.
