### ISSUE TITLE
Add multi -thread support

### ISSUE THREAD

**Issue by acodervic** [fubark/cyber#91]
There are many excellent script language such as LUAJIT, but Luajit is deadly without multi -threaded support, which makes it impossible to complete the more complicated application. Does Cyber plan to add multi -threaded support?

**Comment by fubark** [comment]
The plan is to have green threads built into the language... as well as os threads just like in C but in that case you'd need to provide your own thread safety. As for the host when embedding, there are no plans currently to provide a thread safe VM. Multiple VM's would need to be created in that case.
