### ISSUE TITLE
findAnyRune return unexpected index

### ISSUE THREAD

**Issue by lost22git** [fubark/cyber#92]
|Item|Ver|
|:----:|:----:|
|os|debian 12|
|cyber|0.4-dev|

```cyber
print "👻 koo".findAnyRune("👻").? -- 4
```

**Comment by fubark** [comment]
This looks like a bug with matching UTF-8 strings for `findAnyRune`. Also, we should change the parameter to accept a list of runes instead of a string.

**Comment by fubark** [comment]
This should be fixed.
